### ISSUE TITLE
Missing features for 1.0 release

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo.js#1]
In this issue i will keep a list of features missing for mojo.js 1.0. The list will change regularly. Volunteers are welcome to propose an implementation. We do not port features directly from [Mojolicious](https://mojolicious.org), they also have to use JavaScript best practices. It's best to discuss ideas on [IRC](https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/#mojo.js) (`#mojo.js` on Libera.Chat), so you don't end up wasting your time.

* TypeScript
  - [x] Port everything (one module at a time is fine)
* Cookies:
  - [x] Client/Server cookie encoding/decoding module
  - [x] CookieJar for client
  - [x] Signed cookies for the server
  - [x] Sessions for the server
* Forms (`application/x-www-form-urlencoded`):
  - [x] Support `client.post('/foo', {form: {a: 'b'}})` in the client
  - [x] Support `await ctx.req.form` in the server
* Forms (`multipart/form-data`):
  - [x] Client/server multipart encoding/decoding module (maybe 3rd party?)
  - [x] Design API for the client (`client.post('...', {formData: ...})`, form values and file uploads)
  - [x] Design API for the server (`await ctx.res.formData()`, form values and file uploads)
* Static:
  - [x] `Last-Modified`/`If-Modified-Since`/`Etag` support
  - [x]  `Accept-Ranges` support
  - [x] Design API for sending a static file from an action instead of rendering
* Test:
  - [x] WebSocket methods (`websocketOk`, `sendOk`, `messageOk`, `messageOk`, `finishOk`) 
  - [x] Make `app.newMockContext().someHelper()` work
  - [x] Full test coverage
* Content negotiation
  - [x] `respondTo` method
* General HTTP tools
  - [x] `redirectTo` (options for `status` and maybe some future proofing would be nice)
  - [x] `urlFor` method
* Renderer
  - [x] `renderMaybe` method
  - [x] `renderToString` method
  - [x] Layouts for `ejs` (maybe as part of the plugin, or maybe as a renderer feature)
  - [x] Include for `ejs` (maybe with `renderToString`, or native `ejs` include)
  - [x] gzip compression 
* Commands:
  - [x] `routes` command
  - [x] `get` command (already exists, but needs more HTTP features)
  - [x] `gen-lite-app`, `gen-full-app`, `gen-plugin` (once we have settled on a structure)
* Built-in templates
  - [x] Not found (can be ported directly from Mojolicious)
  - [x] Exception (can be ported directly from Mojolicious)
  - [x] Support for custom not found and exception templates
  - [x] Code preview on development exception page
* Config plugin
  - [x] JSON config (no template for starters, but with support for mode specific files)
* Server
  - [x] `MOJO_SERVER_DEBUG=1` from Mojolicious (without performance loss if not used)
  - [x] HTTPS support
  - [x] Reverse proxy support (`X-Forwarded-For`, `X-Forwarded-Proto`)
* Client
  - [x] Option to follow a certain number of redirects
  - [x] Basic authentication
  - [x] CONNECT and SOCKS proxy support (probably via custom agents like [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) and [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent))
  - [x] HTTPS support (with `insecure` option for self signed certs)
  - [x] gzip compression
* Condition support
  - [x] Design API on router layer (performance is important)
  - [x] Header conditions default pluginversion)
* Hook support
  - [x] Design API (expected to be completely different than the Perl version, maybe events on app object)
* Docs
  - [x] Tutorial giving a basic overview of the framework, similar to the Mojolicious tutorial (Markdown)

All features will need full test coverage. And make sure that there are no performance regressions. An easy test is:
```
$ node examples/hello.js server
...
$ wrk -c 100 -d 10s http://127.0.0.1:3000
...
```

**Comment by jberger** [comment]
Since this is public now I'm going to note that I'm in-progress on websocket testing on this branch: https://github.com/mojolicious/mojo.js/tree/websocket_test_client so that no one duplicates effort

**Comment by kraih** [comment]
Additionally we also have to extend the [server-starter](https://github.com/mojolicious/server-starter) module with directory watch and restart capabilities. It will become the Node.js version of the Morbo development server.

* server-starter
  [ ] File watch and restart

**Comment by Snelius30** [comment]
Glad to see you Kraih to the JS world :) I was miss Mojo there.
While you are not too deep. Please consider starting the project with TypeScript natively. It has too many benefits to avoid.

**Comment by kraih** [comment]
@Snelius30 I'm still undecided about TypeScript. I'd really like to see what `lib/file.js` and `lib/app.js` would look like if they had been converted to TypeScript by an expert. Most large projects i've checked out so far that are using TypeScript seem to overuse generics a lot, making the code much less readable.

**Comment by kraih** [comment]
I've made [a branch](https://github.com/mojolicious/mojo.js/tree/typescript) for TypeScript. It's not very hard to convert everything, but a little inconvenient while APIs are still changing a lot.

**Comment by kraih** [comment]
The project is already in the polishing phase for the 1.0 release. The last few remaining missing features from the list are mostly optional (aside from docs, which are in progress). Now is the time to start experimenting with APIs and figure out which parts don't work quite ideal yet.

**Comment by kraih** [comment]
And porting to TypeScript is finally finished.

**Comment by kraih** [comment]
The generator commands need to be redesigned to work for JavaScript and TypeScript. Open question is how to deal with the `tsconfig.json` and additional dependencies in `package.json`.

**Comment by kraih** [comment]
Main focus now is documentation.

**Comment by kraih** [comment]
Everything is ready for 1.0, just some polishing to do now.

**Comment by kraih** [comment]
We are ready. 😁
