### ISSUE TITLE
May want to differentiate from Koa.js

### ISSUE THREAD

**Issue by EvanCarroll** [mojolicious/mojo.js#2]
This is almost the very same syntax that Koa.js has, you may consider merging the project or using it and its ecosystem as a reference implementation

    router.get('/path/:x', async (ctx, next) => {
      console.log(ctx.params.x);
      await next;
    });
    
See also,

* https://koajs.com/
* https://github.com/koajs/
* https://www.npmjs.com/package/koa-router

**Comment by kraih** [comment]
We are familiar with Koa.js, but the two projects have very different goals i'm afraid.
