### ISSUE TITLE
Incorrect object check

### ISSUE THREAD

**Issue by TheAthlete** [mojolicious/mojo.js#36]
I noticed that the code incorrectly checks that the variable is an object. For example: [_formData](https://github.com/mojolicious/mojo.js/blob/b98d211267726eaba52520ef053d01b4abd6d45d/src/user-agent.ts#L187). The problem is that `typeof null === 'object"`. Correct implementation: [isObject](https://github.com/vuejs/vue/blob/05d05c0e69f446c9bb4ee911fb9004bd386c76ce/src/shared/util.js#L41)

**Comment by kraih** [comment]
`IncomingHttpHeaders` only contains `string | string[] | undefined`.

**Comment by kraih** [comment]
I'm all for being more precise with type checks of course.

**Comment by kraih** [comment]
Thanks, fixed.
