### ISSUE TITLE
run hook stop for commands or commands list

### ISSUE THREAD

**Issue by 6aKa** [mojolicious/mojo.js#56]
I have plugin for database connection. Inside plugin i add stop application hook for closing database connection.

When run `node index.js` i get list of commands, but not exit to shell.
When run `node index.js routes` i get routes, but not exit to shell.

Commands start application, with plugins, but when command finished, does not stop application properly.
Need run application stop hook after command finished or command list printed.

**Comment by kraih** [comment]
The start hook is tied to the server, and the server is never started for the command list. I don't understand your use case i'm afraid.

**Comment by 6aKa** [comment]
Yes server not started, but  all plugins loaded. Part of my redis plugin 
```
  const redis_instanse = createClient(app.config.redis) ?? {};
  redis_instanse.on('error', err => app.log.error(`Redis Client Error: ${err}`));
  redis_instanse.connect();

  app.addHelper('redis', redis_instanse);

  app.addAppHook('stop', () => redis_instanse.quit());
```

When command executed, connection to redis don't closed and command hang up.
I see solution as always run stop application hook.

**Comment by kraih** [comment]
Then why don't you connect in the start hook?

**Comment by 6aKa** [comment]
Because inside command I want use helpers from context like this
```
  const ctx = app.newMockContext();

  const client = await ctx.redis();
  const res = await client.get('TEST');
```

That's why start hook not useful. Connect on demand, in my case something like this and for me this is excess code.
```
  app._redis = null;

  app.addHelper('redis', async (ctx: MojoContext) => {
    if (app._redis == null) {
       app._redis = createClient(app.config.redis['connection'] ?? {});
       app._redis.on('error', err => app.log.error(`Redis Client Error: ${err}`));
       app._redis.connect();
    }

    return redis_instanse;
  });
```

**Comment by kraih** [comment]
I'm starting to see your point. Maybe a `cleanup` hook would make sense that runs at the very end, always. But i'm worried about the implications for testing, since no commands run there.

**Comment by 6aKa** [comment]
I think would be great two hooks `startup` which always run at the begin and `cleanup` which always run at the end.

**Comment by 6aKa** [comment]
Bad idea with additional hooks. Need only two hooks, `start` and `stop`. `start` run before all commands, not only `server`,
`stop` always at the end.

**Comment by kraih** [comment]
That doesn't work, since there are many cases where no command runs at all. Like the test user agent starting and stopping a mock server.

**Comment by kraih** [comment]
Since nobody came up with a better idea we now have two hooks, `command:after` and `server:stop`.
