### ISSUE TITLE
Dark mode logo helpful

### ISSUE THREAD

**Issue by markstos** [mojolicious/mojo.js#61]
The text of the logo appears almost black-on-black in dark mode.

Modern HTML makes it pretty easy to specify an alternate dark-mode image:
https://dev.to/dailydevtips1/light-and-dark-mode-image-in-html-lji

![image](https://user-images.githubusercontent.com/25829/154101987-f895207d-dc99-4fb1-a05b-219a22091e3c.png)

**Comment by kraih** [comment]
Thanks, added.
