### ISSUE TITLE
Will mojo be its own client?

### ISSUE THREAD

**Issue by rizen** [mojolicious/mojo.js#65]
Feathers.js is its own client which is useful to not only standardize web socket communication, but provide helpers for synchronizing data between client and server. Is this something planned for mojo.js, or already possible, or not happening?

https://docs.feathersjs.com/api/client.html

**Comment by dotandimet** [comment]
There already is a full-featured web client in mojo.js: https://github.com/mojolicious/mojo.js/blob/main/docs/User-Agent.md

**Comment by kraih** [comment]
Browser support is not currently planned, but i'm open to the idea and we already have most necessary abstractions in place.
