### ISSUE TITLE
Format being skipped on view rendering

### ISSUE THREAD

**Issue by ralyodio** [mojolicious/mojo.js#96]
`await ctx.render({ view: 'deals/category', format: 'json'}, { deals });` the `category.html.tmpl` is being loaded instead of `category.json.tmpl` file.

**Comment by kraih** [comment]
It appears this was missed when porting the renderer from Perl to TypeScript. https://github.com/mojolicious/mojo.js/blob/27fa8a13600229f235eb5c509e29ea0cc13aeb9d/src/renderer.ts#L68

**Comment by kraih** [comment]
And fixed. https://github.com/mojolicious/mojo.js/commit/b8aa5076747a78bcee849a1485925ad5f8a53be8

**Comment by ralyodio** [comment]
when will this be released?

**Comment by kraih** [comment]
4 hours ago. 😉

**Comment by ralyodio** [comment]
got it and confirmed it works.
